### ISSUE TITLE
Issues with file indentation

### ISSUE THREAD

**Issue by xelra** [lunixbochs/actualvim#56]
I've noticed some weird behaviour with file indentation, when using `>`, `<` or `tab` and `s-tab` in insert mode.

It's hard to explain. The cursor doesn't maintain the correct position and the UI response for that line is incorrect afterwards.

Also using `=` doesn't seem to work. Doing a `gg=G` has no effect.

**Comment by lunixbochs** [comment]
if vim uses tabs and sublime uses spaces, the indentation will mess up on sync.

`:set expandtab ts=4` or set sublime to indent using tabs to verify

**Comment by xelra** [comment]
Yeah, it works if the tabsettings between Sublime and Neovim are the same. `detect_indentation` needs to be off and mixed indent files will confuse it.

`=` doesn't work, even with the same tab settings between Sublime, Neovim and the file.

**Comment by lunixbochs** [comment]
Can you test again as of c82e16c? Tab settings should be synced now. It can sync in either direction, controlled by the `indent_priority` actualvim setting.

**Comment by xelra** [comment]
On https://github.com/lunixbochs/actualvim/commit/b6c6b539a6d1278d0e7e11e6a160353dacd3ee06.

I'm not sure whether it happened after https://github.com/lunixbochs/actualvim/commit/c82e16c21049cbb315ed37f94559dea50965538a.

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 410, in <lambda>
    run_callback(name, vel, lambda: vel.__class__.__dict__[name](vel))
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\actual.py", line 56, in on_activated
    self.v.activate()
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\view.py", line 233, in activate
    self.sync_to_vim()
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\view.py", line 300, in sync_to_vim
    self.sel_to_vim(force)
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\view.py", line 327, in sel_to_vim
    b = self.vim_rowcol(sel.b)
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\view.py", line 132, in vim_rowcol
    vcol = len(line[:col].decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by lunixbochs** [comment]
Hah, it passed my test for the wrong reason. Broken in 76b38658c52e6fe7de3162acce3f5443e4ccb6a5, fixed in 76b3865

**Comment by lunixbochs** [comment]
This should be completely fixed, can you confirm your test passes so I can close this?

**Comment by xelra** [comment]
It's really hard to tell, because of the other bug where it doesn't update the view. So I can't really tell what it did, because it requires additional input.

**Comment by lunixbochs** [comment]
Did some tests locally and it looks fine, closing in favor of the neovim bugs tracked by #41

The delayed update problem is also fixed by the neovim changes, but they're still a WIP.
